name: base
channels:
  - conda-forge
  - bioconda
  - defaults
  - pip
dependencies:
  - numpy=1.26.3
  - pandas=2.1.4
  - typeguard=4.1.5
  - bioconda::gffread
  - bioconda::gffcompare
  - bedtools
  - scikit-learn
  - gtfparse
  - matplotlib
  - seaborn
  - pysam
